// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBankApi.Models.DbContext;

namespace NBankApi.Migrations
{
    [DbContext(typeof(DbContextNBank))]
    partial class DbContextNBankModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("NBankApi.Models.DataBase.Clients", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("MunicipalityColid")
                        .HasColumnType("int");

                    b.Property<string>("cellphone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("document")
                        .HasColumnType("int");

                    b.Property<int>("document_type")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_location")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("MunicipalityColid");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Collects", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AuthorizationCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Creditsid")
                        .HasColumnType("int");

                    b.Property<int?>("Currencysid")
                        .HasColumnType("int");

                    b.Property<int?>("Invoiceid")
                        .HasColumnType("int");

                    b.Property<int?>("Partnersid")
                        .HasColumnType("int");

                    b.Property<decimal>("collection")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("idInvoice")
                        .HasColumnType("int");

                    b.Property<int>("idPartner")
                        .HasColumnType("int");

                    b.Property<DateTime>("paymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("paymentType")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Creditsid");

                    b.HasIndex("Currencysid");

                    b.HasIndex("Invoiceid");

                    b.HasIndex("Partnersid");

                    b.ToTable("Recaudos");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Credits", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Clientsid")
                        .HasColumnType("int");

                    b.Property<int?>("Currencysid")
                        .HasColumnType("int");

                    b.Property<int>("PaidInstallament")
                        .HasColumnType("int");

                    b.Property<bool>("acceptConditions")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("id_currency")
                        .HasColumnType("int");

                    b.Property<decimal>("installamentAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("installment_count")
                        .HasColumnType("int");

                    b.Property<decimal>("insurancePremium")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("next_cutoff_date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("outstanding_balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("overdue_balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("past_due_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("payment_frequency")
                        .HasColumnType("int");

                    b.Property<int?>("perfilid")
                        .HasColumnType("int");

                    b.Property<DateTime>("star_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("state")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.HasIndex("Clientsid");

                    b.HasIndex("Currencysid");

                    b.HasIndex("perfilid");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Currencys", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("currency_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("currency_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("iso_alpha_2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("iso_alpha_3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Divisas");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.FinancialProfiles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Clientsid")
                        .HasColumnType("int");

                    b.Property<int?>("Currencysid")
                        .HasColumnType("int");

                    b.Property<decimal>("expense")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("id_client")
                        .HasColumnType("int");

                    b.Property<int>("id_credit")
                        .HasColumnType("int");

                    b.Property<int>("id_money")
                        .HasColumnType("int");

                    b.Property<int>("income_range_label")
                        .HasColumnType("int");

                    b.Property<decimal>("max_income")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("min_income")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.HasIndex("Clientsid");

                    b.HasIndex("Currencysid");

                    b.ToTable("PerfilesMonetarios");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.FinancialStatus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("cuota")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("idInvoice")
                        .HasColumnType("int");

                    b.Property<decimal>("mora")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("seguro")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.ToTable("EstadosFinancieros");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Invoice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Creditsid")
                        .HasColumnType("int");

                    b.Property<decimal>("current_balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("estadoDeRecudoid")
                        .HasColumnType("int");

                    b.Property<int>("id_credit")
                        .HasColumnType("int");

                    b.Property<string>("invoice_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("on_time_payment")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("Creditsid");

                    b.HasIndex("estadoDeRecudoid");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.MunicipalityCol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("municipality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.NBankMembers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("documentNum")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("hassPass")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<int>("rol")
                        .HasColumnType("int");

                    b.Property<int>("typeDoc")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Miembros");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Partners", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("aliadoid")
                        .HasColumnType("int");

                    b.Property<decimal>("collection_commission")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("hashApiPass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("nit")
                        .HasColumnType("int");

                    b.Property<int>("partner_type")
                        .HasColumnType("int");

                    b.Property<string>("partners_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("aliadoid");

                    b.ToTable("Aliados");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Clients", b =>
                {
                    b.HasOne("NBankApi.Models.DataBase.MunicipalityCol", null)
                        .WithMany("clientes")
                        .HasForeignKey("MunicipalityColid");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Collects", b =>
                {
                    b.HasOne("NBankApi.Models.DataBase.Credits", null)
                        .WithMany("recaudos")
                        .HasForeignKey("Creditsid");

                    b.HasOne("NBankApi.Models.DataBase.Currencys", null)
                        .WithMany("recaudos")
                        .HasForeignKey("Currencysid");

                    b.HasOne("NBankApi.Models.DataBase.Invoice", null)
                        .WithMany("recaudos")
                        .HasForeignKey("Invoiceid");

                    b.HasOne("NBankApi.Models.DataBase.Partners", null)
                        .WithMany("recaudos")
                        .HasForeignKey("Partnersid");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Credits", b =>
                {
                    b.HasOne("NBankApi.Models.DataBase.Clients", null)
                        .WithMany("creditos")
                        .HasForeignKey("Clientsid");

                    b.HasOne("NBankApi.Models.DataBase.Currencys", null)
                        .WithMany("creditos")
                        .HasForeignKey("Currencysid");

                    b.HasOne("NBankApi.Models.DataBase.FinancialProfiles", "perfil")
                        .WithMany()
                        .HasForeignKey("perfilid");

                    b.Navigation("perfil");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.FinancialProfiles", b =>
                {
                    b.HasOne("NBankApi.Models.DataBase.Clients", null)
                        .WithMany("perfiles")
                        .HasForeignKey("Clientsid");

                    b.HasOne("NBankApi.Models.DataBase.Currencys", null)
                        .WithMany("perfiles")
                        .HasForeignKey("Currencysid");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Invoice", b =>
                {
                    b.HasOne("NBankApi.Models.DataBase.Credits", null)
                        .WithMany("facturas")
                        .HasForeignKey("Creditsid");

                    b.HasOne("NBankApi.Models.DataBase.FinancialStatus", "estadoDeRecudo")
                        .WithMany()
                        .HasForeignKey("estadoDeRecudoid");

                    b.Navigation("estadoDeRecudo");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Partners", b =>
                {
                    b.HasOne("NBankApi.Models.DataBase.Partners", "aliado")
                        .WithMany()
                        .HasForeignKey("aliadoid");

                    b.Navigation("aliado");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Clients", b =>
                {
                    b.Navigation("creditos");

                    b.Navigation("perfiles");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Credits", b =>
                {
                    b.Navigation("facturas");

                    b.Navigation("recaudos");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Currencys", b =>
                {
                    b.Navigation("creditos");

                    b.Navigation("perfiles");

                    b.Navigation("recaudos");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Invoice", b =>
                {
                    b.Navigation("recaudos");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.MunicipalityCol", b =>
                {
                    b.Navigation("clientes");
                });

            modelBuilder.Entity("NBankApi.Models.DataBase.Partners", b =>
                {
                    b.Navigation("recaudos");
                });
#pragma warning restore 612, 618
        }
    }
}
